import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'
import { Barlow } from 'next/font/google'
import './globals.css'

const barlow = Barlow({
  variable: '--font-barlow',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${barlow.variable} antialiased`}>
        {children}
        <Toaster
          position='top-center'
          reverseOrder={false}
          toastOptions={{
            duration: 5000,
          }}
        />
      </body>
    </html>
  )
}
